FROM openjdk
WORKDIR usr/lib
ADD ./target/Userauthenticationservice-0.0.1-SNAPSHOT.jar /usr/lib/Userauthenticationservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Userauthenticationservice-0.0.1-SNAPSHOT.jar"]